# Generated by Django 5.1.15 on 2026-09-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_participantprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
