# Generated by Django 5.1.15 on 2026-09-11 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0002_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.TextField(blank=True, default='')),
                ('track', models.CharField(blank=True, max_length=120, null=True)),
                ('build_mode', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('repo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('demo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('demo_video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('winner', 'Winner'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='hackathons.hackathon')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='teams.team')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
                'unique_together': {('hackathon', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/attachments/%Y/%m/')),
                ('display_name', models.CharField(max_length=255)),
                ('attachment_type', models.CharField(choices=[('source_code', 'Source Code'), ('deck', 'Deck / Presentation'), ('demo_video', 'Demo Video'), ('screenshot', 'Screenshot'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
