# Generated by Django 5.1.15 on 2026-09-11 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonregistration',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_registration', to='teams.team'),
        ),
        migrations.AddField(
            model_name='judgingcriterion',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_criteria', to='hackathons.hackathon'),
        ),
        migrations.AlterUniqueTogether(
            name='hackathonregistration',
            unique_together={('hackathon', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='judgingcriterion',
            unique_together={('hackathon', 'name')},
        ),
    ]
