# Generated by Django 5.1.15 on 2026-09-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=120)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('deliverables', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('starter', 'Starter'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statements', to='hackathons.hackathon')),
            ],
            options={
                'ordering': ['category', 'title'],
                'unique_together': {('hackathon', 'slug')},
            },
        ),
    ]
