# Generated by Django 5.1.15 on 2026-09-17 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_problemstatement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='require_participant_enrollment',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ParticipantEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_preference', models.CharField(choices=[('create_team', 'I want to lead a team'), ('join_team', 'I already have a team'), ('need_team', 'Help me find a team'), ('solo', 'I plan to build solo')], max_length=30)),
                ('primary_role', models.CharField(choices=[('developer', 'Software developer'), ('data_ai', 'Data / AI'), ('designer', 'Designer / UX'), ('product', 'Product / business'), ('domain_expert', 'Domain expert'), ('student', 'Student / learner'), ('other', 'Other')], max_length=30)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('attendance_mode', models.CharField(choices=[('onsite', 'On-site'), ('online', 'Online'), ('flexible', 'Either / flexible')], default='flexible', max_length=20)),
                ('motivation', models.TextField(blank=True, default='')),
                ('agreed_to_rules', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('approved', 'Approved'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_enrollments', to='hackathons.hackathon')),
                ('selected_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_participants', to='hackathons.problemstatement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('hackathon', 'user')},
            },
        ),
    ]
